// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XiaLM.P101.Quartz.Db;

namespace XiaLM.P101.Quartz.Migrations
{
    [DbContext(typeof(BaseDBContext))]
    [Migration("20190115082311_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("XiaLM.P101.Quartz.Db.Entities.Tb_Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssemblyName");

                    b.Property<DateTime>("BeginTime");

                    b.Property<string>("ClassName");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Cron");

                    b.Property<DateTime?>("EndTime");

                    b.Property<int>("IntervalSecond");

                    b.Property<string>("JobGroup");

                    b.Property<string>("JobName");

                    b.Property<string>("Remark");

                    b.Property<int>("RunTimes");

                    b.Property<int>("TriggerType");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("Url");

                    b.Property<int>("Valid");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
